In [323]:
import requests
import pandas
import numpy

In [324]:
url = "https://dummyjson.com/products"
response = requests.get(url)
print(response)
data = response.json()
print(response.status_code)

df = pandas.DataFrame(data)
df

<Response [200]>
200

                                             products  total  skip  limit
0   {'id': 1, 'title': 'Essence Mascara Lash Princ...    194     0     30
1   {'id': 2, 'title': 'Eyeshadow Palette with Mir...    194     0     30
2   {'id': 3, 'title': 'Powder Canister', 'descrip...    194     0     30
3   {'id': 4, 'title': 'Red Lipstick', 'descriptio...    194     0     30
4   {'id': 5, 'title': 'Red Nail Polish', 'descrip...    194     0     30
5   {'id': 6, 'title': 'Calvin Klein CK One', 'des...    194     0     30
6   {'id': 7, 'title': 'Chanel Coco Noir Eau De', ...    194     0     30
7   {'id': 8, 'title': 'Dior J'adore', 'descriptio...    194     0     30
8   {'id': 9, 'title': 'Dolce Shine Eau de', 'desc...    194     0     30
9   {'id': 10, 'title': 'Gucci Bloom Eau de', 'des...    194     0     30
10  {'id': 11, 'title': 'Annibale Colombo Bed', 'd...    194     0     30
11  {'id': 12, 'title': 'Annibale Colombo Sofa', '...    194     0     30
12  {'id': 13, 'title': 'Bedside Table African Che...    194     0     30
13  {'id': 14, 'title': 'Knoll Saarinen Executive ...    194     0     30
14  {'id': 15, 'title': 'Wooden Bathroom Sink With...    194     0     30
15  {'id': 16, 'title': 'Apple', 'description': 'F...    194     0     30
16  {'id': 17, 'title': 'Beef Steak', 'description...    194     0     30
17  {'id': 18, 'title': 'Cat Food', 'description':...    194     0     30
18  {'id': 19, 'title': 'Chicken Meat', 'descripti...    194     0     30
19  {'id': 20, 'title': 'Cooking Oil', 'descriptio...    194     0     30
20  {'id': 21, 'title': 'Cucumber', 'description':...    194     0     30
21  {'id': 22, 'title': 'Dog Food', 'description':...    194     0     30
22  {'id': 23, 'title': 'Eggs', 'description': 'Fr...    194     0     30
23  {'id': 24, 'title': 'Fish Steak', 'description...    194     0     30
24  {'id': 25, 'title': 'Green Bell Pepper', 'desc...    194     0     30
25  {'id': 26, 'title': 'Green Chili Pepper', 'des...    194     0     30
26  {'id': 27, 'title': 'Honey Jar', 'description'...    194     0     30
27  {'id': 28, 'title': 'Ice Cream', 'description'...    194     0     30
28  {'id': 29, 'title': 'Juice', 'description': 'R...    194     0     30
29  {'id': 30, 'title': 'Kiwi', 'description': 'Nu...    194     0     30

In [325]:
df = pandas.DataFrame(data['products'])
df

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,"{'width': 18.11, 'height': 28.38, 'depth': 22.17}",3 year warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,"{'width': 21.63, 'height': 16.48, 'depth': 29.84}",1 month warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
5,6,Calvin Klein CK One,CK One by Calvin Klein is a classic unisex fra...,fragrances,49.99,1.89,4.37,29,"[fragrances, perfumes]",Calvin Klein,...,"{'width': 29.36, 'height': 27.76, 'depth': 20.72}",1 week warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Very disappointed!'...",90 days return policy,9,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
6,7,Chanel Coco Noir Eau De,Coco Noir by Chanel is an elegant and mysterio...,fragrances,129.99,16.51,4.26,58,"[fragrances, perfumes]",Chanel,...,"{'width': 24.5, 'height': 25.7, 'depth': 25.98}",3 year warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Highly impressed!',...",No return policy,1,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
7,8,Dior J'adore,J'adore by Dior is a luxurious and floral frag...,fragrances,89.99,14.72,3.80,98,"[fragrances, perfumes]",Dior,...,"{'width': 27.67, 'height': 28.28, 'depth': 11.83}",1 week warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great value for mon...",7 days return policy,10,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
8,9,Dolce Shine Eau de,Dolce Shine by Dolce & Gabbana is a vibrant an...,fragrances,69.99,0.62,3.96,4,"[fragrances, perfumes]",Dolce & Gabbana,...,"{'width': 27.28, 'height': 29.88, 'depth': 18.3}",3 year warranty,Ships in 1 month,Low Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",7 days return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
9,10,Gucci Bloom Eau de,Gucci Bloom by Gucci is a floral and captivati...,fragrances,79.99,14.39,2.74,91,"[fragrances, perfumes]",Gucci,...,"{'width': 20.92, 'height': 21.68, 'depth': 11.2}",6 months warranty,Ships overnight,In Stock,"[{'rating': 1, 'comment': 'Very dissatisfied!'...",No return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
10,11,Annibale Colombo Bed,The Annibale Colombo Bed is a luxurious and el...,furniture,1899.99,8.57,4.77,88,"[furniture, beds]",Annibale Colombo,...,"{'width': 28.16, 'height': 25.36, 'depth': 17.28}",1 year warranty,Ships in 1 month,In Stock,"[{'rating': 2, 'comment': 'Would not recommend...",No return policy,1,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
11,12,Annibale Colombo Sofa,The Annibale Colombo Sofa is a sophisticated a...,furniture,2499.99,14.40,3.92,60,"[furniture, sofas]",Annibale Colombo,...,"{'width': 12.75, 'height': 20.55, 'depth': 19.06}",Lifetime warranty,Ships in 1 week,In Stock,"[{'rating': 3, 'comment': 'Very unhappy with m...",7 days return policy,1,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
12,13,Bedside Table African Cherry,The Bedside Table in African Cherry is a styli...,furniture,299.99,19.09,2.87,64,"[furniture, bedside tables]",Furniture Co.,...,"{'width': 13.47, 'height': 24.99, 'depth': 27.35}",5 year warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Excellent quality!'...",7 days return policy,3,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
13,14,Knoll Saarinen Executive Conference Chair,The Knoll Saarinen Executive Conference Chair ...,furniture,499.99,2.01,4.88,26,"[furniture, office chairs]",Knoll,...,"{'width': 13.81, 'height': 7.5, 'depth': 5.62}",2 year warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Waste of money!', '...",60 days return policy,5,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
14,15,Wooden Bathroom Sink With Mirror,The Wooden Bathroom Sink with Mirror is a uniq...,furniture,799.99,8.80,3.59,7,"[furniture, bathroom]",Bath Trends,...,"{'width': 7.98, 'height': 8.88, 'depth': 28.46}",3 year warranty,Ships in 3-5 business days,Low Stock,"[{'rating': 4, 'comment': 'Fast shipping!', 'd...",60 days return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
15,16,Apple,"Fresh and crisp apples, perfect for snacking o...",groceries,1.99,12.62,4.19,8,[fruits],NaN,...,"{'width': 13.66, 'height': 11.01, 'depth': 9.73}",3 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Very satisfied!', '...",90 days return policy,7,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
16,17,Beef Steak,"High-quality beef steak, great for grilling or...",groceries,12.99,9.61,4.47,86,[meat],NaN,...,"{'width': 18.9, 'height': 5.77, 'depth': 18.57}",3 year warranty,Ships overnight,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",60 days return policy,43,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
17,18,Cat Food,Nutritious cat food formulated to meet the die...,groceries,8.99,9.58,3.13,46,"[pet supplies, cat food]",NaN,...,"{'width': 18.08, 'height': 9.26, 'depth': 21.86}",1 year warranty,Ships overnight,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,18,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
18,19,Chicken Meat,"Fresh and tender chicken meat, suitable for va...",groceries,9.99,13.70,3.19,97,[meat],NaN,...,"{'width': 11.03, 'height': 22.11, 'depth': 16.01}",1 year warranty,Ships in 1 month,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
19,20,Cooking Oil,"Versatile cooking oil suitable for frying, sau...",groceries,4.99,9.33,4.80,10,[cooking essentials],NaN,...,"{'width': 19.95, 'height': 27.54, 'depth': 24.86}",Lifetime warranty,Ships in 1-2 business days,In Stock,"[{'rating': 5, 'comment': 'Very happy with my ...",30 days return policy,46,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
20,21,Cucumber,"Crisp and hydrating cucumbers, ideal for salad...",groceries,1.49,0.16,4.07,84,[vegetables],NaN,...,"{'width': 12.8, 'height': 28.38, 'depth': 21.34}",2 year warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
21,22,Dog Food,Specially formulated dog food designed to prov...,groceries,10.99,10.27,4.55,71,"[pet supplies, dog food]",NaN,...,"{'width': 16.93, 'height': 27.15, 'depth': 9.29}",No warranty,Ships in 1-2 business days,In Stock,"[{'rating': 5, 'comment': 'Excellent quality!'...",60 days return policy,43,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
22,23,Eggs,"Fresh eggs, a versatile ingredient for baking,...",groceries,2.99,11.05,2.53,9,[dairy],NaN,...,"{'width': 11.42, 'height': 7.44, 'depth': 16.95}",1 week warranty,Ships in 1 week,In Stock,"[{'rating': 3, 'comment': 'Disappointing produ...",No return policy,32,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
23,24,Fish Steak,"Quality fish steak, suitable for grilling, bak...",groceries,14.99,4.23,3.78,74,[seafood],NaN,...,"{'width': 14.95, 'height': 26.31, 'depth': 11.27}",1 month warranty,Ships in 3-5 business days,In Stock,"[{'rating': 2, 'comment': 'Would not buy again...",60 days return policy,50,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
24,25,Green Bell Pepper,"Fresh and vibrant green bell pepper, perfect f...",groceries,1.29,0.16,3.25,33,[vegetables],NaN,...,"{'width': 15.33, 'height': 26.65, 'depth': 14.44}",1 month warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Highly recommended!...",30 days return policy,12,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
25,26,Green Chili Pepper,"Spicy green chili pepper, ideal for adding hea...",groceries,0.99,1.00,3.66,3,[vegetables],NaN,...,"{'width': 15.38, 'height': 18.12, 'depth': 19.92}",2 year warranty,Ships in 1 week,Low Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",30 days return policy,39,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
26,27,Honey Jar,"Pure and natural honey in a convenient jar, pe...",groceries,6.99,14.40,3.97,34,[condiments],NaN,...,"{'width': 9.28, 'height': 21.72, 'depth': 17.74}",1 month warranty,Ships in 1-2 business days,In Stock,"[{'rating': 1, 'comment': 'Very disappointed!'...",90 days return policy,47,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
27,28,Ice Cream,"Creamy and delicious ice cream, available in v...",groceries,5.49,8.69,3.39,27,[desserts],NaN,...,"{'width': 14.83, 'height': 15.07, 'depth': 24.2}",1 month warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Very pleased!', 'da...",No return policy,42,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
28,29,Juice,"Refreshing fruit juice, packed with vitamins a...",groceries,3.99,12.06,3.94,50,[beverages],NaN,...,"{'width': 18.56, 'height': 21.46, 'depth': 28.02}",6 months warranty,Ships in 1 week,In Stock,"[{'rating': 5, 'comment': 'Excellent quality!'...",No return policy,25,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
29,30,Kiwi,"Nutrient-rich kiwi, perfect for snacking or ad...",groceries,2.49,15.22,4.93,99,[fruits],NaN,...,"{'width': 19.4, 'height': 18.67, 'depth': 17.13}",6 months warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Highly recommended!...",7 days return policy,30,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...

In [326]:
df.columns

Index(['id', 'title', 'description', 'category', 'price', 'discountPercentage',
       'rating', 'stock', 'tags', 'brand', 'sku', 'weight', 'dimensions',
       'warrantyInformation', 'shippingInformation', 'availabilityStatus',
       'reviews', 'returnPolicy', 'minimumOrderQuantity', 'meta', 'images',
       'thumbnail'],
      dtype='object')

In [327]:
df = df[['price','discountPercentage','rating']]
df

      price  discountPercentage  rating
0      9.99               10.48    2.56
1     19.99               18.19    2.86
2     14.99                9.84    4.64
3     12.99               12.16    4.36
4      8.99               11.44    4.32
5     49.99                1.89    4.37
6    129.99               16.51    4.26
7     89.99               14.72    3.80
8     69.99                0.62    3.96
9     79.99               14.39    2.74
10  1899.99                8.57    4.77
11  2499.99               14.40    3.92
12   299.99               19.09    2.87
13   499.99                2.01    4.88
14   799.99                8.80    3.59
15     1.99               12.62    4.19
16    12.99                9.61    4.47
17     8.99                9.58    3.13
18     9.99               13.70    3.19
19     4.99                9.33    4.80
20     1.49                0.16    4.07
21    10.99               10.27    4.55
22     2.99               11.05    2.53
23    14.99                4.23    3.78
24     1.29                0.16    3.25
25     0.99                1.00    3.66
26     6.99               14.40    3.97
27     5.49                8.69    3.39
28     3.99               12.06    3.94
29     2.49               15.22    4.93

In [328]:
df.columns

Index(['price', 'discountPercentage', 'rating'], dtype='object')

In [329]:
df.isna().sum()

price                 0
discountPercentage    0
rating                0
dtype: int64

In [330]:
df.dtypes

price                 float64
discountPercentage    float64
rating                float64
dtype: object

In [331]:
y = df.iloc[:,0]
df = df.drop(columns=['price'])
x = df

In [332]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [333]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)

x_test = scaler.transform(x_test)

In [334]:
from sklearn.linear_model import LinearRegression

linear = LinearRegression()
linear = linear.fit(x_train,y_train)

y_pred = linear.predict(x_test)

In [335]:
print(linear.coef_)      # m
print(linear.intercept_) # c

[ 17.89764272 117.83357227]
152.78999999999976

In [336]:
from sklearn.metrics import mean_absolute_percentage_error,r2_score

print(mean_absolute_percentage_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

21.483542898245584
-0.09350678701992976

In [337]:
from sklearn.preprocessing import PolynomialFeatures

pf = PolynomialFeatures(degree=2)

x_train_poly = pf.fit_transform(x_train)
x_test_poly = pf.transform(x_test)

In [338]:
model1 = LinearRegression()
model1.fit(x_train_poly,y_train)

y_poly = model1.predict(x_test_poly)
y_poly

array([157.28019998,  24.49083523, 454.18223492, 135.93106358,
       146.66492648,  91.28196702,  -8.4145295 ,  -4.71655132,
         4.13005895])

In [339]:
print(mean_absolute_percentage_error(y_test,y_poly))
print(r2_score(y_test,y_poly))

18.925778232779887
-0.26823690937080236