# XG Boosting 
===============

# Extreme gradient boosting

>> one tree bulit and when the error occurred , the next tree is formed by focusing on the error , 
   like that the last tree is formed with zero error. 

>> underfitting , overfitting , error

In [23]:
import pandas
from xgboost import XGBClassifier 

data = {
    "hours" : [1,2,4,5],
    "result": [0,1,1,1]        # 0 >> fail , 1 >> pass
}

In [24]:
df = pandas.DataFrame(data)
df

   hours  result
0      1       0
1      2       1
2      4       1
3      5       1

In [25]:
x = df[["hours"]]
y = df[["result"]]

In [26]:
model = XGBClassifier()
model.fit(x,y)
y_pred = model.predict(x)
y_pred

array([1, 1, 1, 1])

In [27]:
y

   result
0       0
1       1
2       1
3       1

In [28]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y,y_pred))

0.75